language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
before_script: 
sudo pip install ds18b20
sudo apt-get install python-pip
sudo apt-get install git
sudo pip install gspread oauth2client

script: 
