language: python
python:
  
  - "2.7"
  - "3.4"

# command to install dependencies
install: 
sudo apt-get install python-pip
sudo pip install gspread oauth2client
# command to run tests
script: nosetests
